[theme]
primaryColor = "#FFFFFF"          # White for text and key accents
backgroundColor = "#FF3008"       # DoorDash Red for the main background
secondaryBackgroundColor = "#FFEFEA" # Soft Coral for chat bubbles or sections
textColor = "#FFFFFF"             # White for maximum readability on the red background
font = "sans serif"               # Clean, modern sans-serif font
