[theme]
primaryColor = "#FFFFFF"          # Clean White for text and highlights
backgroundColor = "#FF3E30"       # Modern Red for the main background (less harsh than pure red)
secondaryBackgroundColor = "#FFDAD4" # Light Coral for chat bubbles or sections
textColor = "#FFFFFF"             # White for high contrast against the red background
font = "sans serif"               # Modern, clean font (like Roboto or Arial)
